Repository rsksmart/rns-sdk, pull requests merged in 2021-12, with the labels that each got.

#11 RSK Registrar SDK
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/AddrResolver.ts
  src/RNS.ts
  src/RSKRegistrar.ts
  src/hash.ts
  src/index.ts
  src/random.ts
  test/addrResolver.test.ts
  test/e2e.test.ts
  test/rns.test.ts
  test/rskRegistrar.test.ts
  test/rskregistrar/bytesUtils.json
  test/rskregistrar/fifsAddrRegistrar.json
  test/rskregistrar/namePrice.json
  test/rskregistrar/rskOwner.json
  test/rskregistrar/tokenRegistrar.json
  test/util.ts
  webpack.config.js
  yarn.lock
Labels: documentation, enhancement

#13 Create publish.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: dev

#15 Fix build + fix readme
  README.md
  package-lock.json
  package.json
Labels: bug

#17 Fix target
  package-lock.json
  package.json
  webpack.config.js
Labels: bug
